
//!
//! AUTOGENERATED BASED ON A SET OF JSON FILES, DO NOT EDIT MANUALLY
//!

use strum_macros::{EnumDiscriminants, FromRepr};

use crate::error::domains::CoreCode;
use crate::error::domains::CompilerCode;

#[derive(Clone, Debug, EnumDiscriminants, Eq, PartialEq, serde::Deserialize, serde::Serialize)]
#[strum_discriminants(name(DomainCode))]
#[strum_discriminants(derive(FromRepr))]
#[strum_discriminants(vis(pub))]
#[repr(i32)]
pub enum Kind {
   Core(CoreCode) = 2,
   Compiler(CompilerCode) = 1,
}

impl Kind {
    pub fn domain_code(&self) -> i32 {
        let domain: DomainCode = self.clone().into();
        domain as i32
    }
    pub fn component_code(&self) -> i32 {
        match self {
         Kind::Core(component) => component.clone() as i32,
         Kind::Compiler(component) => component.clone() as i32,

        }
    }
}
